version: '2.4'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile.production
      cache_from:
        - biryukovpyu/devops-for-programmers-project-lvl1
    image: biryukovpyu/devops-for-programmers-project-lvl1
    command: ["npm", "test"]
    mem_limit: 768M
