version: '2.4'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: devopsforprogrammersprojectlvl1
    volumes:
      - .:/usr/src/app
    command: ["npm", "test"]
    mem_limit: 768M
