version: '2.4'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile.production
    image: biryukovpyu/devops-for-programmers-project-lvl1
    depends_on:
      - db
    command: ["npm", "test"]
    mem_limit: 768M

  db:
    image: postgres:13-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${NODOS_DB_USERNAME}
      POSTGRES_PASSWORD: ${NODOS_DB_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata      
    volumes:
      - pg-data:/var/lib/postgresql/data
    mem_limit: 512M
    restart: always

volumes:
  pg-data:
