FROM node:14.6
WORKDIR /app

# Copy package.json, package-lock.json*, npm-shrinkwrap.json* and install modules
COPY ["package.json", "package-lock.json*", "npm-shrinkwrap.json*", "./"]
RUN npm install

# Copy src
COPY . .

EXPOSE 8080
CMD ["npm", "start"]
